apiVersion: v1
kind: ServiceAccount
metadata:
  name: winter-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: winter-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-role
subjects:
  - kind: ServiceAccount
    name: winter-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: winter
  namespace: default
  labels:
    app: winter
spec:
  replicas: 5
  selector:
    matchLabels:
      app: winter
  template:
    metadata:
      labels:
        app: winter
    spec:
      serviceAccountName: winter-sa
      containers:
      - name: winter
        imagePullPolicy: Always
        image: aguxez/winter:0.0.1-rc
        env:
        - name: RECEPTOR_PORT
          value: "6969"
        - name: RELEASE_COOKIE
          value: "set-cookie"
        - name: RELEASE_DISTRIBUTION
          value: name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RELEASE_NODE
          value: "winter@$(POD_IP)"
        ports:
        - containerPort: 6969
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: winter-nodes
  namespace: default
  labels:
    app: winter
spec:
  selector:
    app: winter
  clusterIP: None
  ports:
    - name: winter-service-port
      port: 6969
      targetPort: 6969
